"""Initial migration for journal_club

Revision ID: 65487931a101
Revises: 
Create Date: 2024-10-21 14:22:27.988278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65487931a101'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctoral_student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=150), nullable=False),
    sa.Column('ki_email', sa.String(length=120), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ki_email')
    )
    op.create_table('journal_club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('DOI', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('place', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('journal_club_id', sa.Integer(), nullable=False),
    sa.Column('attended_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['journal_club_id'], ['journal_club.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['doctoral_student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'journal_club_id', name='unique_attendance')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    op.drop_table('journal_club')
    op.drop_table('doctoral_student')
    # ### end Alembic commands ###
